## Universidade do Estado do Amazonas
### Disciplina: Redes Neurais Artificiais 2025/1
### Integrantes: 
> Emanuelle Marreira - 2215080035

> Afonso Garcia - 1615080003

> Italo Ferreira - 2215080012

> João Carvalho - 2215080040 

## Identificador

In [48]:
identificador = (5+3+2+0)%4
print(identificador)

2


## Bibliotecas

In [49]:
import random
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
np.set_printoptions(precision=4, suppress=True)

## Definição do Neurônio Perceptron

In [50]:
class NeuronioPerceptron:
    def __init__(self, taxa_de_aprendizado = 0.1, n_features = 2, vies = -1):
        self.taxa_de_aprendizado = taxa_de_aprendizado
        self.n_features = n_features
        self.pesos_iniciais = np.random.uniform(-0.5, 0.5, size = self.n_features + 1)
        #self.pesos_iniciais = [-0.5441, 0.5562, -0.4074]
        self.pesos = self.pesos_iniciais.copy()
        self.epocas = 0
        self.total_ajustes_pesos = 0
        self.vies = vies

    def ativacao(self, theta):
        return np.where(theta >= 0, 1, 0)

    def prever(self, X_com_vies):
        entrada = np.dot(X_com_vies, self.pesos)
        print(f"{X_com_vies} * {self.pesos} = {np.round(entrada, 4)}")
        return self.ativacao(entrada)
    
    def realizar_ajuste(self, erro, xi):
        self.pesos = self.pesos + self.taxa_de_aprendizado * erro * xi
        self.total_ajustes_pesos += 1

    def treino(self, X_treino, y_treino):
        print(f"Pesos iniciais (w0, w1, w2): {self.pesos_iniciais}")
        X_treino_vies = np.insert(X_treino, 0, self.vies, axis = 1)

        convergiu = False
        while not convergiu:
            self.epocas += 1
            print(f"\n**********{self.epocas}a época**********\n")
            erros_na_epoca = 0
            ocorreu_erro = False

            for xi, yd in zip(X_treino_vies, y_treino):
                y_previsto = self.prever(xi)
                erro = yd - y_previsto

                if erro != 0:
                    print(f"!!!ERRO em: {xi} | {yd} - {y_previsto} = {erro}")
                    self.realizar_ajuste(erro, xi)
                    erros_na_epoca += 1
                    ocorreu_erro = True
            
            if not ocorreu_erro:
                convergiu = True
        print(f"\nConvergência alcançada!")
        print(f"Pesos finais: {self.pesos}")
        return self


In [51]:
# Teste com o exemplo da professora
X = [(2,2),(4,4)]
Y = [1,0]
neuronio_perceptron = NeuronioPerceptron(taxa_de_aprendizado = 0.1, n_features = 2)
neuronio_perceptron.treino(X, Y)
print(f"Número total de ajustes nos pesos: {neuronio_perceptron.total_ajustes_pesos}")
print(f"Número de épocas até a convergência: {neuronio_perceptron.epocas}")

Pesos iniciais (w0, w1, w2): [-0.4303  0.333  -0.2543]

**********1a época**********

[-1  2  2] * [-0.4303  0.333  -0.2543] = 0.5878
[-1  4  4] * [-0.4303  0.333  -0.2543] = 0.7453
!!!ERRO em: [-1  4  4] | 0 - 1 = -1

**********2a época**********

[-1  2  2] * [-0.3303 -0.067  -0.6543] = -1.1122
!!!ERRO em: [-1  2  2] | 1 - 0 = 1
[-1  4  4] * [-0.4303  0.133  -0.4543] = -0.8547

**********3a época**********

[-1  2  2] * [-0.4303  0.133  -0.4543] = -0.2122
!!!ERRO em: [-1  2  2] | 1 - 0 = 1
[-1  4  4] * [-0.5303  0.333  -0.2543] = 0.8453
!!!ERRO em: [-1  4  4] | 0 - 1 = -1

**********4a época**********

[-1  2  2] * [-0.4303 -0.067  -0.6543] = -1.0122
!!!ERRO em: [-1  2  2] | 1 - 0 = 1
[-1  4  4] * [-0.5303  0.133  -0.4543] = -0.7547

**********5a época**********

[-1  2  2] * [-0.5303  0.133  -0.4543] = -0.1122
!!!ERRO em: [-1  2  2] | 1 - 0 = 1
[-1  4  4] * [-0.6303  0.333  -0.2543] = 0.9453
!!!ERRO em: [-1  4  4] | 0 - 1 = -1

**********6a época**********

[-1  2  2] * [-0.5303 -0.

## Parte 1 - Resolvendo um problema linearmente separável

### Definição dos dados

In [52]:
dados = np.fromfile('dataAll.txt', dtype = np.float64)
dados = dados.reshape(-1,1,3)
print(f"Dados carregados: {dados.shape}")
dados = dados.reshape(-1, 3)
X = dados[:, [0,1]]  # x1 e x2
yd = dados[:, 2]   # yd
print(f"X = {X[:5]}...")
print(f"yd = {yd[:5]}...")

Dados carregados: (1000, 1, 3)
X = [[-363.7884  244.1423]
 [ 328.7572 -256.7658]
 [-164.9827  613.2164]
 [ 536.5905  764.9575]
 [ 314.2297  343.8375]]...
yd = [0. 1. 0. 0. 0.]...


### Treinamento 

In [53]:
neuronio_perceptron = NeuronioPerceptron(taxa_de_aprendizado = 0.1, n_features = 2)
neuronio_perceptron = neuronio_perceptron.treino(X, yd)

print(f"Número total de ajustes nos pesos: {neuronio_perceptron.total_ajustes_pesos}")
print(f"Número de épocas até a convergência: {neuronio_perceptron.epocas}")

Pesos iniciais (w0, w1, w2): [-0.0068  0.0698 -0.3791]

**********1a época**********

[  -1.     -363.7884  244.1423] * [-0.0068  0.0698 -0.3791] = -117.948
[  -1.      328.7572 -256.7658] * [-0.0068  0.0698 -0.3791] = 120.3017
[  -1.     -164.9827  613.2164] * [-0.0068  0.0698 -0.3791] = -243.9907
[ -1.     536.5905 764.9575] * [-0.0068  0.0698 -0.3791] = -252.5401
[ -1.     314.2297 343.8375] * [-0.0068  0.0698 -0.3791] = -108.4104
[  -1.      -87.6395 -306.9783] * [-0.0068  0.0698 -0.3791] = 110.2687
[  -1.     -172.0622 -500.5087] * [-0.0068  0.0698 -0.3791] = 177.7454
[ -1.     727.9602 358.2956] * [-0.0068  0.0698 -0.3791] = -85.0085
!!!ERRO em: [ -1.     727.9602 358.2956] | 1.0 - 0 = 1.0
[ -1.     752.3574 268.3682] * [-0.1068 72.8658 35.4504] = 64335.0265
[  -1.      685.6276 -833.4677] * [-0.1068 72.8658 35.4504] = 20412.1315
[  -1.       11.5324 -588.4802] * [-0.1068 72.8658 35.4504] = -20021.4601
!!!ERRO em: [  -1.       11.5324 -588.4802] | 1.0 - 0 = 1.0
[  -1.     -925.91

### Impressão dos resultados